# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetTokenResponse(UniversalBaseModel):
    access_token: str = pydantic.Field()
    """
    The access token
    """

    token_type: str = pydantic.Field()
    """
    The type of token (typically "Bearer")
    """

    expires_in: typing.Optional[int] = pydantic.Field(default=None)
    """
    Lifetime of the access token in seconds
    """

    refresh_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    The refresh token
    """

    scope: typing.Optional[str] = pydantic.Field(default=None)
    """
    The scope of the access token
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
