# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .stream_as_agent_response import (
        StreamAsAgentResponse,
        StreamAsAgentResponse_AgentRequest,
        StreamAsAgentResponse_Heartbeat,
    )
    from .stream_tasks_response import StreamTasksResponse, StreamTasksResponse_Heartbeat, StreamTasksResponse_TaskEvent
    from .task_query_status_filter import TaskQueryStatusFilter
    from .task_query_status_filter_status import TaskQueryStatusFilterStatus
    from .task_query_update_time_range import TaskQueryUpdateTimeRange
    from .task_stream_request_task_type import TaskStreamRequestTaskType
    from .task_stream_request_task_type_task_type_prefix import TaskStreamRequestTaskTypeTaskTypePrefix
    from .task_stream_request_task_type_task_type_urls import TaskStreamRequestTaskTypeTaskTypeUrls
_dynamic_imports: typing.Dict[str, str] = {
    "StreamAsAgentResponse": ".stream_as_agent_response",
    "StreamAsAgentResponse_AgentRequest": ".stream_as_agent_response",
    "StreamAsAgentResponse_Heartbeat": ".stream_as_agent_response",
    "StreamTasksResponse": ".stream_tasks_response",
    "StreamTasksResponse_Heartbeat": ".stream_tasks_response",
    "StreamTasksResponse_TaskEvent": ".stream_tasks_response",
    "TaskQueryStatusFilter": ".task_query_status_filter",
    "TaskQueryStatusFilterStatus": ".task_query_status_filter_status",
    "TaskQueryUpdateTimeRange": ".task_query_update_time_range",
    "TaskStreamRequestTaskType": ".task_stream_request_task_type",
    "TaskStreamRequestTaskTypeTaskTypePrefix": ".task_stream_request_task_type_task_type_prefix",
    "TaskStreamRequestTaskTypeTaskTypeUrls": ".task_stream_request_task_type_task_type_urls",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "StreamAsAgentResponse",
    "StreamAsAgentResponse_AgentRequest",
    "StreamAsAgentResponse_Heartbeat",
    "StreamTasksResponse",
    "StreamTasksResponse_Heartbeat",
    "StreamTasksResponse_TaskEvent",
    "TaskQueryStatusFilter",
    "TaskQueryStatusFilterStatus",
    "TaskQueryUpdateTimeRange",
    "TaskStreamRequestTaskType",
    "TaskStreamRequestTaskTypeTaskTypePrefix",
    "TaskStreamRequestTaskTypeTaskTypeUrls",
]
